title: Jahan Ali - Portfolio
logo: img/J_profile.jpg
description: <a href="https://www.youtube.com/@Jahan_424 " target="_blank" rel="noopener noreferrer">Youtube | <a href="https://jahanarticles.blogspot.com/2025/03/machine-learning-techniques-machine.html" target="_blank" rel="noopener noreferrer">Blogs |  <a href="https://drive.google.com/file/d/1Qc8NbpVM-oVyKPc-Gj1HA2Hu5fVDCgUl/view?usp=sharing" target="_blank" rel="noopener noreferrer">CV </a>
show_downloads: true
theme: jekyll-theme-minimal


