title: Jahan Ali - Portfolio
logo: img/J_profile.jpg
description: <a href="https://www.youtube.com/@Jahan_424 " target="_blank" rel="noopener noreferrer">Youtube</a>
description: <a href="https://jahanarticles.blogspot.com/p/learning-techniques-what-is-machine.html">Blog Post</a>
show_downloads: true
theme: jekyll-theme-minimal


