title: Jahan Ali - Portfolio
logo: img/J_profile.jpg
description: <a href="https://www.youtube.com/@Jahan_424 " target="_blank" rel="noopener noreferrer">Youtube | <a href="https://jahanarticles.blogspot.com/2025/03/machine-learning-techniques-machine.html" target="_blank" rel="noopener noreferrer">Blogs  </a>
show_downloads: true
theme: jekyll-theme-minimal


